version: 0.2

phases:
  install:
    commands:
      - wget --quiet https://golang.org/dl/go${GO_VERSION}.linux-amd64.tar.gz
      - tar -xzf go${GO_VERSION}.linux-amd64.tar.gz
  build:
    commands:
      - go/bin/go build -o main cmd/popper/main.go

artifacts:
  base-directory: "lambda"
  files:
    - main
